name = "openfeature"
version = "0.6.0"
description = "The Gleam SDK for the OpenFeature specification."
licences = ["Apache-2.0"]
repository = { type = "github", user = "horvathandris", repo = "openfeature-gleam-sdk" }
gleam = ">= 1.0.0"
# links = [{ title = "Website", href = "https://gleam.run" }]


[dependencies]
gleam_stdlib = "~> 0.30 or ~> 1.0"
gleam_otp = ">= 0.10.0 and < 1.0.0"
gleam_erlang = ">= 0.25.0 and < 1.0.0"
worm = ">= 1.0.4 and < 2.0.0"

[dev-dependencies]
gleeunit = "~> 1.0"
